services:
  - type: web
    name: zrl-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash -c "echo 'RENDER START COMMAND EXECUTED!' && sleep 5 && exit 0""
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PROD_DATABASE_URL
        fromDatabase:
          name: zrl-db
          property: connectionString

  - type: db
    name: zrl-db
    engine: postgresql
    plan: free
