services:
  - type: web
    name: zrl-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements_prod.txt && python run_migrations.py"
    startCommand: "gunicorn --bind 0.0.0.0:${PORT} run:app"
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
