services:
  - type: web
    name: zrl-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && cp entrypoint.sh . && cp alembic.ini . && cp -r newZRL/migrations newZRL/ && chmod +x entrypoint.sh"
    startCommand: "sh ./entrypoint.sh"
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PROD_DATABASE_URL
        fromDatabase:
          name: zrl-db
          property: connectionString

  - type: db
    name: zrl-db
    engine: postgresql
    plan: free
