services:
  - type: web
    name: zrl-manager
    env: python
    plan: free
    buildCommand: "pip install -r requirements_prod.txt && chmod +x entrypoint.sh"
    startCommand: "sh ./entrypoint.sh"
    envVars:
      - key: FLASK_CONFIG
        value: production



